import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import { PeopleAction } from "../actions";
import { PeopleInterface } from "../interface";

const Home: NextPage = () => {
  const [people, setPeople] = useState<PeopleInterface[]>([]);
  const [page, setPage] = useState(1);

  useEffect(() => {
    getPeople();
  }, [page]);

  const getPeople = async () => {
    let res = await PeopleAction.get({ page });
    if (res) {
      setPeople(res);
    }
  };

  console.log(people);

  return (
    <div className="w-screen">
      <Head>
        <title>NextJS Star Wars</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col items-center container mx-auto">
        <div className="text-3xl mb-5 font-semibold">STAR WARS PEOPLE</div>
        <div className="flex justify-between w-full mb-5">
          <button
            className="bg-blue-300 py-1 px-4 rounded-md"
            onClick={() => setPage(page - 1)}
          >
            Prevent
          </button>
          <button
            className="bg-blue-300 py-1 px-4 rounded-md"
            onClick={() => setPage(page + 1)}
          >
            Next
          </button>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-3">
          {people?.map((item, index) => (
            <div
              className="flex flex-col border rounded-lg px-6 py-4 w-full"
              key={index}
            >
              <div>
                <span className="font-semibold">Name:</span> {item?.name}
              </div>
              <div>
                <span className="font-semibold">Height::</span> {item?.height}
              </div>
              <div>
                <span className="font-semibold">Birth Year::</span>{" "}
                {item?.birth_year}
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};

export default Home;
